/* Additional record code for TrainSimulation.Train generated by the OpenModelica Compiler OpenModelica v1.16.0-dev.03 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "TrainSimulation.Train_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

